// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpchgodejuyqpeezozec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY2hnb2RlanV5cXBlZXpvemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTA3MzQsImV4cCI6MjA1OTI2NjczNH0.V7hO7fSDVwM6evbZvZwlLCwhk_ENQ7Sa6pnGEMFznTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);